name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: prepare
        run: |
          sudo apt-get -y install libboost-dev libfl-dev lcov

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: build
        run: |
          make coverage

      - name: Coveralls upload
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: lcov
          file: build/lcov.info
