name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: prepare
        run: |
          sudo apt-get -y install libboost-dev flex lcov
      - uses: actions/checkout@v4
      - name: build
        run: |
          make

